### ISSUE TITLE
Upgrade Rosetta specification version

### ISSUE THREAD

**Issue by bisgardo** [Concordium/concordium-rosetta#27]
We implement spec version 1.4.10, but as of this writing, the version listed as "current" in the docs is 1.4.12.

**Comment by abizjak** [comment]
Is there a changelog?

**Comment by bisgardo** [comment]
They list changes on the [release page](https://github.com/coinbase/rosetta-specifications/releases).

**Comment by bisgardo** [comment]
It doesn't look like much has changed between these versions.
