### ISSUE TITLE
Migrate the Rosetta API to GRPCv2

### ISSUE THREAD

**Issue by rasmus-kirk** [Concordium/concordium-rosetta#52]
We need to migrate this API to use the GRPCv2 calls instead. 

**Sub-tasks**
- [x] `main.rs`
- [x] `account.rs`
- [x] `amount.rs`
- [x] `block.rs`
- [x] `construction.rs`
- [x] `network.rs`
- [x] `query.rs`
- [x] `transaction.rs`

**Comment by smh1001** [comment]
@rasmus-kirk I think this Epic is all done. If so please close it
